# NicknameColors Plugin for PocketMine-MP Config File!
# Plugin Created in 9/21/20 By BabosApple

form-api-usage: "true"
# Disable and Enable FormAPI

# view the change-log in my discord server! make sure to join